// <auto-generated />
using System;
using AppTodoList.Api.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppTodoList.Api.Persistencia.Migraciones
{
    [DbContext(typeof(ListaTareasDbContext))]
    [Migration("20260929112010_FechasInicioFin")]
    partial class FechasInicioFin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("AppTodoList.Api.Dominio.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResponsableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResponsableId");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("AppTodoList.Api.Dominio.UsuarioEjemplo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Alex"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Sam"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Taylor"
                        });
                });

            modelBuilder.Entity("AppTodoList.Api.Dominio.Tarea", b =>
                {
                    b.HasOne("AppTodoList.Api.Dominio.UsuarioEjemplo", "Responsable")
                        .WithMany("Tareas")
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("AppTodoList.Api.Dominio.UsuarioEjemplo", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
